import React, { useEffect, useMemo, useState } from "react";
import { Activity, Check, ChevronDown, Copy, Download, Landmark, Link2, Plus, Radio, RefreshCcw, Trash2, WifiOff } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { formatMoney, formatRr, toNumber } from "@/lib/gold";
import { toast } from "sonner";

const EA_DOWNLOAD = "/api/mt5/ea";
const pkt = (value?: string | Date | null) => value ? new Date(value).toLocaleString("en-PK", { timeZone: "Asia/Karachi", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }) : "—";
const masked = (key: string) => key.length < 10 ? "••••••••" : `${key.slice(0, 4)}••••••••${key.slice(-3)}`;
const moneyOrDash = (value: string | number | null | undefined) => value == null ? "—" : formatMoney(value);
function connectionState(lastPing?: string | Date | null) { if (!lastPing) return { label: "Never connected", tone: "neutral" }; const elapsed = Date.now() - new Date(lastPing).getTime(); return elapsed <= 10_000 ? { label: "Connected", tone: "live" } : elapsed <= 60_000 ? { label: "Idle", tone: "idle" } : { label: "Offline", tone: "offline" }; }
function CopyValue({ value, label }: { value: string; label: string }) { const copy = async () => { try { await navigator.clipboard.writeText(value); toast.success(`${label} copied.`); } catch { toast.error("Copy is unavailable in this browser."); } }; return <button className="mt5-copy" onClick={() => void copy()} aria-label={`Copy ${label}`} title={`Copy ${label}`}><Copy size={14} /></button>; }

function AccountMetric({ label, value, detail, tone = "neutral" }: { label: string; value: string; detail: string; tone?: string }) { return <article className={`mt5-account-metric ${tone}`}><span>{label}</span><strong className="data-text">{value}</strong><small>{detail}</small></article>; }

export function Mt5LiveView({ account, accounts, onJournalNow }: any) {
  const accountInput = useMemo(() => account?.id ? ({ accountId: account.id }) : undefined, [account?.id]);
  const [historyPage, setHistoryPage] = useState(1);
  useEffect(() => setHistoryPage(1), [account?.id]);
  const historyInput = useMemo(() => account?.id ? ({ accountId: account.id, page: historyPage, pageSize: 20 }) : undefined, [account?.id, historyPage]);
  const workspace = trpc.mt5.workspace.useQuery(accountInput!, { enabled: Boolean(accountInput), refetchInterval: 2_500, refetchOnWindowFocus: true });
  const history = trpc.mt5.history.useQuery(historyInput!, { enabled: Boolean(historyInput), refetchInterval: 5_000, refetchOnWindowFocus: true });
  const createConnection = trpc.mt5.createConnection.useMutation(); const setActive = trpc.mt5.setConnectionActive.useMutation(); const deleteConnection = trpc.mt5.deleteConnection.useMutation(); const utils = trpc.useUtils();
  const [addOpen, setAddOpen] = useState(false); const [label, setLabel] = useState(""); const [linkAccountId, setLinkAccountId] = useState<number | undefined>(account?.id); const [guideOpen, setGuideOpen] = useState(true); const [createdApiKey, setCreatedApiKey] = useState<string | null>(null);
  useEffect(() => { setLinkAccountId(account?.id); }, [account?.id]);
  const allConnections = workspace.data?.connections ?? []; const connections = allConnections.filter((connection: any) => connection.accountId === account?.id); const openPositions = (workspace.data?.openPositions ?? []).filter((position: any) => position.accountId === account?.id); const activeConnection = connections.find((connection: any) => connection.active); const positions = (history.data?.positions ?? []).filter((position: any) => position.accountId === account?.id); const historyTotal = history.data?.total; const availableAccounts = account?.id ? [account] : []; const serverUrl = typeof window === "undefined" ? "/api/mt5" : `${window.location.origin}/api/mt5`;
  const refresh = () => { void utils.mt5.workspace.invalidate(); void utils.mt5.history.invalidate(); };
  const saveConnection = async () => { if (!label.trim() || !linkAccountId) return; try { const created = await createConnection.mutateAsync({ accountId: linkAccountId, label: label.trim() }); setCreatedApiKey(created?.apiKey ?? null); toast.success("MT5 connection created. Copy its API key into the EA now."); setAddOpen(false); setLabel(""); refresh(); } catch (error: any) { toast.error(error.message || "Could not create MT5 connection."); } };
  const historyStatus = !activeConnection ? "Create a connection to begin sync." : activeConnection.lastHistoryStatus === "FAILED" ? `History batch failed: ${activeConnection.lastHistoryMessage || "Check the EA log and connection."}` : activeConnection.lastHistorySync ? `${typeof historyTotal === "number" ? historyTotal : activeConnection.historySyncedCount} closed positions synced · ${pkt(activeConnection.lastHistorySync)} PKT` : activeConnection.lastHistoryAttempt ? `${activeConnection.lastHistoryMessage || "History batch received."} Waiting for completion.` : "No historical batch has reached Gold Journal yet. The terminal is sending account summaries, but not history.";
  return <section className="mt5-live-view"><header className="section-heading mt5-heading"><div><span className="eyebrow">DIRECT MT5 SYNC</span><h2>MT5 Live</h2><p>Live balances, equity, floating P&amp;L, open positions, and historical closes synchronize automatically into the linked Trade Log.</p></div><Button onClick={() => setAddOpen(true)} disabled={!availableAccounts.length}><Plus size={16} /> Add connection</Button></header>
    <section className="mt5-account-panel panel"><div className="mt5-section-head"><div><span className="eyebrow">{account?.name || "ACTIVE ACCOUNT"}</span><h3>MT5 account snapshot</h3></div><Button variant="outline" size="sm" onClick={() => { void workspace.refetch(); void history.refetch(); }}><RefreshCcw size={14} /> Refresh</Button></div>{activeConnection?.balance == null ? <div className="mt5-empty compact"><Landmark size={24} /><h3>Waiting for MT5 account metrics</h3><p>Attach EA v1.13 to any chart. Balance, equity, free margin, and floating P&amp;L appear after its next summary event.</p></div> : <><div className="mt5-account-grid"><AccountMetric label="Balance" value={moneyOrDash(activeConnection.balance)} detail={activeConnection.currency || "MT5 currency"} tone="gold" /><AccountMetric label="Equity" value={moneyOrDash(activeConnection.equity)} detail="Balance + floating P&L" /><AccountMetric label="Floating P&L" value={moneyOrDash(activeConnection.floatingPnl)} detail="Open position result" tone={toNumber(activeConnection.floatingPnl) >= 0 ? "profit" : "loss"} /><AccountMetric label="Free margin" value={moneyOrDash(activeConnection.freeMargin)} detail={`Margin ${moneyOrDash(activeConnection.margin)}`} /></div><p className="mt5-account-detail">Login {activeConnection.mt5Login || "—"} · {activeConnection.brokerServer || "MT5 terminal"} · Last terminal contact {pkt(activeConnection.lastPing)} PKT</p></>}</section>
    <section className="mt5-connection-section"><div className="mt5-section-head"><div><span className="eyebrow">CONNECTIONS</span><h3>MT5 Connections</h3></div><span className="mt5-sync-indicator"><Activity size={14} /> {workspace.isFetching ? "Refreshing…" : "Live refresh every 2.5s"}</span></div>{connections.length ? <div className="mt5-connection-grid">{connections.map((connection: any) => { const state = connectionState(connection.lastPing); return <article className="mt5-connection-card" key={connection.id}><header><div><span className={`mt5-status ${state.tone}`}><i /> {state.label}</span><h4>{connection.label}</h4><small>{connection.accountName}</small></div><label className="mt5-switch"><input type="checkbox" checked={connection.active} onChange={event => void setActive.mutateAsync({ connectionId: connection.id, active: event.target.checked }).then(refresh).catch((error: any) => toast.error(error.message || "Connection could not be updated."))} /><span /></label></header><div className="mt5-secret-row"><span>API KEY</span><code>{connection.apiKeyMasked || masked(connection.apiKey || "")}</code>{connection.apiKey ? <CopyValue value={connection.apiKey} label="API key" /> : null}</div><div className="mt5-secret-row"><span>SERVER URL</span><code>{serverUrl}</code><CopyValue value={serverUrl} label="Server URL" /></div><footer><small>{connection.lastPing ? `Last contact ${pkt(connection.lastPing)} PKT` : "Waiting for the first EA ping."}</small><button className="text-danger" onClick={() => { if (!window.confirm(`Delete ${connection.label}? Historical MT5 records remain with this account.`)) return; void deleteConnection.mutateAsync({ connectionId: connection.id, confirmed: true }).then(() => { toast.success("MT5 connection deleted."); refresh(); }).catch((error: any) => toast.error(error.message || "Could not delete connection.")); }}><Trash2 size={14} /> Delete</button></footer></article>; })}</div> : <div className="mt5-empty"><Link2 size={28} /><h3>No MT5 connection yet</h3><p>Create one for a Gold Journal account, then copy its key into the Expert Advisor.</p><Button onClick={() => setAddOpen(true)} disabled={!availableAccounts.length}><Plus size={16} /> Add first connection</Button></div>}</section>
    <section className={`mt5-guide panel ${guideOpen ? "open" : ""}`}><button className="mt5-guide-toggle" onClick={() => setGuideOpen(!guideOpen)}><div><span className="eyebrow">SETUP GUIDE · EA v1.13</span><h3>How to connect MT5 and backfill history</h3></div><ChevronDown size={18} /></button>{guideOpen && <ol><li><div><strong>Replace the earlier EA build</strong><p>Download EA v1.13. It sends balance, equity, floating P&amp;L, live positions, and history using the broker’s explicit UTC offset so Gold Journal can classify sessions in PKT correctly.</p></div><a className="button-link" href={EA_DOWNLOAD} download="GoldJournal_EA.mq5"><Download size={15} /> Download EA v1.13</a></li><li><div><strong>Install in MT5</strong><p>Copy it to <code>C:\Users\[YourName]\AppData\Roaming\MetaQuotes\Terminal\[ID]\MQL5\Experts\</code>. In MT5, open Navigator → Expert Advisors, right-click, then Refresh.</p></div></li><li><div><strong>Set the broker UTC offset</strong><p>For this MT5 terminal, leave <code>BrokerUtcOffsetHours</code> at <code>3</code>. The EA converts the UTC+3 broker time into the correct PKT UTC+5 session on Gold Journal.</p></div></li><li><div><strong>Allow the server URL</strong><p>In MT5: Tools → Options → Expert Advisors. Enable “Allow WebRequests for listed URL,” add the server URL below, then click OK.</p><div className="mt5-inline-copy"><code>{serverUrl}</code><CopyValue value={serverUrl} label="Server URL" /></div></div></li><li><div><strong>Restart the EA once</strong><p>Remove Gold Journal EA from the chart, then drag it back on and paste the matching API key and server URL. This restarts the historical scan. Keep MT5 open until the MT5 Live status shows synced positions; those trades then appear automatically in Trade Log.</p></div></li></ol>}</section>
    <section className="mt5-position-section"><div className="mt5-section-head"><div><span className="eyebrow">{account?.name || "ACTIVE ACCOUNT"}</span><h3>Open positions</h3></div><span className="mt5-live-dot"><Radio size={14} /> Live</span></div>{openPositions.length ? <div className="mt5-position-grid">{openPositions.map((position: any) => <article key={position.ticket} className={`mt5-position-card ${toNumber(position.floatingPnl) >= 0 ? "profit" : "loss"}`}><header><div><h4>{position.symbol}</h4><span className={`side-badge ${position.direction.toLowerCase()}`}>{position.direction}</span></div><strong className={`data-text ${toNumber(position.floatingPnl) >= 0 ? "positive" : "negative"}`}>{formatMoney(position.floatingPnl)}</strong></header><div className="mt5-metrics"><span>Risk <b>{formatMoney(position.riskUsd)}</b></span><span>Reward <b>{formatMoney(position.rewardUsd)}</b></span><span>R:R <b>{formatRr(position.riskUsd, position.rewardUsd)}</b></span></div><footer><span>Open {position.openPrice}</span><span>SL {position.slPrice || "—"}</span><span>TP {position.tpPrice || "—"}</span><span>{position.lots} lots · {pkt(position.openTime)} PKT</span></footer></article>)}</div> : <div className="mt5-empty compact"><WifiOff size={24} /><h3>No open positions in MT5</h3><p>Positions will appear in both MT5 Live and Trade Log after an active connection receives data from EA v1.13.</p></div>}</section>
    <section className="mt5-closed-section panel"><div className="mt5-section-head"><div><span className="eyebrow">HISTORICAL CLOSED POSITIONS</span><h3>MT5 trade history</h3><p className="mt5-history-status">{historyStatus}</p></div><button className="icon-button" onClick={() => { void workspace.refetch(); void history.refetch(); }} aria-label="Refresh MT5 history"><RefreshCcw size={16} /></button></div>{positions.length ? <><div className="mt5-table-wrap"><table className="mt5-table"><thead><tr><th>Date</th><th>Symbol</th><th>Direction</th><th>Open</th><th>Close</th><th>Risk</th><th>Reward</th><th>R:R</th><th>P&amp;L</th><th>Result</th><th>Trade Log</th></tr></thead><tbody>{positions.map((position: any) => <tr key={position.ticket}><td>{pkt(position.closeTime)}</td><td>{position.symbol}</td><td><span className={`side-badge ${position.direction.toLowerCase()}`}>{position.direction}</span></td><td>{position.openPrice}</td><td>{position.closePrice}</td><td>{formatMoney(position.riskUsd)}</td><td>{formatMoney(position.rewardUsd)}</td><td>{formatRr(position.riskUsd, position.rewardUsd)}</td><td className={`data-text ${toNumber(position.realizedPnl) >= 0 ? "positive" : "negative"}`}>{formatMoney(position.realizedPnl)}</td><td>{position.result?.replace("_", " ")}</td><td><span className="mt5-journaled"><Check size={13} /> {position.journaled ? "Synced" : "Syncing"}</span></td></tr>)}</tbody></table></div>{(history.data?.pageCount ?? 1) > 1 && <div className="table-pagination"><span>Page {history.data?.page} of {history.data?.pageCount} · {history.data?.total} closed positions</span><div><Button variant="outline" size="sm" disabled={historyPage === 1 || history.isFetching} onClick={() => setHistoryPage(page => page - 1)}>Previous</Button><Button variant="outline" size="sm" disabled={historyPage >= (history.data?.pageCount ?? 1) || history.isFetching} onClick={() => setHistoryPage(page => page + 1)}>Next</Button></div></div>}</> : <p className="mt5-no-closed">{history.isLoading ? "Loading MT5 history…" : "Historical MT5 closes appear here as EA v1.13 backfills them, then they are added automatically to Trade Log."}</p>}</section>
    <Dialog open={Boolean(createdApiKey)} onOpenChange={open => { if (!open) setCreatedApiKey(null); }}><DialogContent><DialogHeader><DialogTitle>Copy your MT5 API key</DialogTitle><DialogDescription>This key is shown once. Save it in the EA now; the server stores only an encrypted copy.</DialogDescription></DialogHeader>{createdApiKey && <div className="mt5-secret-row"><code>{createdApiKey}</code><CopyValue value={createdApiKey} label="API key" /></div>}<div className="dialog-actions"><Button onClick={() => setCreatedApiKey(null)}>Done</Button></div></DialogContent></Dialog><Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent><DialogHeader><DialogTitle>Add MT5 connection</DialogTitle><DialogDescription>Create one private API key for a Gold Journal account. You will copy it into the MT5 Expert Advisor.</DialogDescription></DialogHeader><div className="mt5-add-form"><label>Connection label<Input value={label} onChange={event => setLabel(event.target.value)} placeholder="GFT 10K Account" /></label><label>Link to account<select value={linkAccountId ?? ""} onChange={event => setLinkAccountId(Number(event.target.value))}><option value="">Select account</option>{availableAccounts.map((item: any) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div><div className="dialog-actions"><Button variant="outline" onClick={() => setAddOpen(false)}>Cancel</Button><Button disabled={!label.trim() || !linkAccountId || createConnection.isPending} onClick={() => void saveConnection()}>{createConnection.isPending ? "Creating…" : "Create connection"}</Button></div></DialogContent></Dialog></section>;
}
